CREATE SEQUENCE SEQ_URL_ALIAS;

CREATE TABLE TB_URL_ALIAS (
    ID BIGINT DEFAULT nextval('SEQ_URL_ALIAS'),
    LONG_URL VARCHAR(2048) NOT NULL ,
    URL_ALIAS VARCHAR(64) NOT NULL ,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT PK_URL_ALIAS PRIMARY KEY (ID),
    CONSTRAINT UQ_URL_ALIAS UNIQUE (URL_ALIAS)
);